#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# vim: set ts=4 sw=4 sts=4 et:

from argparse import ArgumentParser
from sys import stdin, stdout
from os.path import splitext

import pygal
import yaml


ARG_TYPES = ('svg', 'png', 'html')
DEFAULT_TYPE = 'Line'
DEFAULT_STYLE = 'DefaultStyle'


class GoogleClassicStyle(pygal.style.Style):
    """A Google Spreadsheet Classic theme"""

    background = 'transparent'
    plot_background = 'transparent'
    foreground = '#757575'
    foreground_strong = '#757575'
    foreground_subtle = '#cccccc'
    colors = (
        '#4285f4',  # ~ RoyalBlue1
        '#db4437',  # ~ tomato3
        '#f4b400',  # ~ DarkGoldenrod2
        '#93c47d',  # ~ dark sea green
        '#ff6d00',  # ~ DarkOrange1
        '#46bdc6',  # ~ medium turquoise
    )

    value_colors = colors
    font_family = 'Roboto,RobotoDraft,Helvetica,Arial,sans-serif'
    title_font_size = 14
    legend_font_size = 14
    value_font_size = 12


class GoogleStandardStyle(pygal.style.Style):
    """A Google Spreadsheet Standard theme"""

    background = 'transparent'
    plot_background = 'transparent'
    foreground = '#757575'
    foreground_strong = '#757575'
    foreground_subtle = '#cccccc'
    colors = (
        '#4285f4',  # ~ RoyalBlue1
        '#ea4335',  # ~ brown2
        '#fbbc04',  # ~ DarkGoldenrod1
        '#34a853',  # ~ sea green
        '#ff6d01',  # ~ DarkOrange1
        '#46bdc6',  # ~ medium turquoise
    )

    value_colors = colors
    font_family = 'Roboto,RobotoDraft,Helvetica,Arial,sans-serif'
    title_font_size = 14
    legend_font_size = 14
    value_font_size = 12


class GoogleSimpleLightStyle(pygal.style.Style):
    """A Google Spreadsheet Simple Light theme"""

    background = 'transparent'
    plot_background = 'transparent'
    foreground = '#757575'
    foreground_strong = '#757575'
    foreground_subtle = '#cccccc'
    colors = (
        '#5891ad',  # ~ cadet blue
        '#004561',  # ~ DodgerBlue4
        '#ff6f31',  # ~ chocolate1
        '#1c7685',  # ~ DeepSkyBlue4
        '#0f45a8',  # ~ DodgerBlue4
        '#4cdc8b',  # ~ SeaGreen2
    )

    value_colors = colors
    font_family = 'Roboto,RobotoDraft,Helvetica,Arial,sans-serif'
    title_font_size = 14
    legend_font_size = 14
    value_font_size = 12


class GoogleStreamlineStyle(pygal.style.Style):
    """A Google Spreadsheet Streamline theme"""

    background = 'transparent'
    plot_background = 'transparent'
    foreground = '#1a1a1a'
    foreground_strong = '#1a1a1a'
    foreground_subtle = '#cccccc'
    colors = (
        '#1a9988',  # ~ cyan4
        '#2d729d',  # ~ SteelBlue4
        '#1f3e78',  # ~ RoyalBlue4
        '#eb5600',  # ~ OrangeRed2
        '#ff99ac',  # ~ LightPink2
        '#ffd4b8',  # ~ peach puff
    )

    value_colors = colors
    font_family = 'Roboto,RobotoDraft,Helvetica,Verdana,sans-serif'
    title_font_size = 14
    legend_font_size = 14
    value_font_size = 12


class GoogleParadigmStyle(pygal.style.Style):
    """A Google Spreadsheet Paradigm theme"""

    background = 'transparent'
    plot_background = 'transparent'
    foreground = '#071924'
    foreground_strong = '#071924'
    foreground_subtle = '#cccccc'
    colors = (
        '#002f4a',  # ~ midnight blue
        '#b85741',  # ~ coral3
        '#ad8463',  # ~ LightSalmon3
        '#009384',  # ~ cyan4
        '#eddac9',  # ~ AntiqueWhite2
        '#6fc8d6',  # ~ DarkSlateGray3
    )

    value_colors = colors
    font_family = 'Roboto,RobotoDraft,Helvetica,Georgia,sans-serif'
    title_font_size = 14
    legend_font_size = 14
    value_font_size = 12


class GoogleShiftStyle(pygal.style.Style):
    """A Google Spreadsheet Shift theme"""

    background = 'transparent'
    plot_background = 'transparent'
    foreground = '#233a44'
    foreground_strong = '#233a44'
    foreground_subtle = '#cccccc'
    colors = (
        '#00796b',  # ~ turquoise4
        '#bf8659',  # ~ LightSalmon3
        '#00435e',  # ~ DodgerBlue4
        '#d9563f',  # ~ coral3
        '#e7bb63',  # ~ sandy brown
        '#144cf5',  # ~ DodgerBlue3
    )

    value_colors = colors
    font_family = 'Roboto,RobotoDraft,Helvetica,Verdana,sans-serif'
    title_font_size = 14
    legend_font_size = 14
    value_font_size = 12


class GoogleMomentumStyle(pygal.style.Style):
    """A Google Spreadsheet Momentum theme"""

    background = 'transparent'
    plot_background = 'transparent'
    foreground = '#424242'
    foreground_strong = '#424242'
    foreground_subtle = '#cccccc'
    colors = (
        '#c0791b',  # ~ dark goldenrod
        '#0b6374',  # ~ DeepSkyBlue4
        '#fd5b58',  # ~ tomato
        '#27278b',  # ~ RoyalBlue4
        '#8dd8d3',  # ~ PaleTurquoise3
        '#d7e6a3',  # ~ pale goldenrod
    )

    value_colors = colors
    font_family = 'Roboto,RobotoDraft,Helvetica,Verdana,sans-serif'
    title_font_size = 14
    legend_font_size = 14
    value_font_size = 12


class GoogleEarthyStyle(pygal.style.Style):
    """A Google Spreadsheet Earthy theme"""

    background = 'transparent'
    plot_background = 'transparent'
    foreground = '#3e5656'
    foreground_strong = '#3e5656'
    foreground_subtle = '#cccccc'
    colors = (
        '#b0725d',  # ~ salmon3
        '#8f3738',  # ~ IndianRed4
        '#e79a3c',  # ~ tan2
        '#447874',  # ~ aquamarine4
        '#d2d479',  # ~ khaki3
        '#8b8948',  # ~ khaki4
    )

    value_colors = colors
    font_family = 'Roboto,RobotoDraft,Helvetica,Arial,sans-serif'
    title_font_size = 14
    legend_font_size = 14
    value_font_size = 12


class GoogleEnergeticStyle(pygal.style.Style):
    """A Google Spreadsheet Energetic theme"""

    background = 'transparent'
    plot_background = 'transparent'
    foreground = '#2c2c4d'
    foreground_strong = '#2c2c4d'
    foreground_subtle = '#cccccc'
    colors = (
        '#1d2384',  # ~ midnight blue
        '#e44819',  # ~ OrangeRed2
        '#f5a69b',  # ~ LightPink2
        '#a68057',  # ~ NavajoWhite4
        '#f4aa11',  # ~ DarkGoldenrod2
        '#d1eb60',  # ~ DarkOliveGreen2
    )

    value_colors = colors
    font_family = 'Roboto,RobotoDraft,Helvetica,Arial,sans-serif'
    title_font_size = 14
    legend_font_size = 14
    value_font_size = 12


class GoogleOceanStyle(pygal.style.Style):
    """A Google Spreadsheet Ocean theme"""

    background = 'transparent'
    plot_background = 'transparent'
    foreground = '#005975'
    foreground_strong = '#005975'
    foreground_subtle = '#cccccc'
    colors = (
        '#0078b8',  # ~ DodgerBlue3
        '#0091de',  # ~ DeepSkyBlue3
        '#00a3fa',  # ~ DeepSkyBlue2
        '#42bdff',  # ~ SteelBlue1
        '#6eccff',  # ~ SteelBlue1
        '#8fe1ff',  # ~ CadetBlue2
    )

    value_colors = colors
    font_family = 'Roboto,RobotoDraft,Helvetica,Arial,sans-serif'
    title_font_size = 14
    legend_font_size = 14
    value_font_size = 12


class GoogleCozyStyle(pygal.style.Style):
    """A Google Spreadsheet Cozy theme"""

    background = 'transparent'
    plot_background = 'transparent'
    foreground = '#344846'
    foreground_strong = '#344846'
    foreground_subtle = '#cccccc'
    colors = (
        '#00535c',  # ~ dark slate gray
        '#cd840e',  # ~ orange3
        '#9f545c',  # ~ PaleVioletRed4
        '#d9c1ad',  # ~ AntiqueWhite3
        '#d5e8ac',  # ~ pale goldenrod
        '#3862b5',  # ~ RoyalBlue3
    )

    value_colors = colors
    font_family = 'Roboto,RobotoDraft,Helvetica,Arial,sans-serif'
    title_font_size = 14
    legend_font_size = 14
    value_font_size = 12


class GoogleGroovyStyle(pygal.style.Style):
    """A Google Spreadsheet Groovy theme"""

    background = 'transparent'
    plot_background = 'transparent'
    foreground = '#1a2f40'
    foreground_strong = '#1a2f40'
    foreground_subtle = '#cccccc'
    colors = (
        '#c93232',  # ~ brown3
        '#e27228',  # ~ chocolate2
        '#0d398c',  # ~ DodgerBlue4
        '#fc4479',  # ~ VioletRed2
        '#dcdc12',  # ~ yellow3
        '#1f95d1',  # ~ DeepSkyBlue3
    )

    value_colors = colors
    font_family = 'Roboto,RobotoDraft,Helvetica,Verdana,sans-serif'
    title_font_size = 14
    legend_font_size = 14
    value_font_size = 12


class GoogleCalmStyle(pygal.style.Style):
    """A Google Spreadsheet Calm theme"""

    background = 'transparent'
    plot_background = 'transparent'
    foreground = '#242f26'
    foreground_strong = '#242f26'
    foreground_subtle = '#cccccc'
    colors = (
        '#608f66',  # ~ DarkSeaGreen4
        '#274766',  # ~ dark slate gray
        '#dfa398',  # ~ RosyBrown3
        '#ab9084',  # ~ rosy brown
        '#613942',  # ~ gray29
        '#e68ca5',  # ~ PaleVioletRed2
    )

    value_colors = colors
    font_family = 'Roboto,RobotoDraft,Helvetica,Verdana,sans-serif'
    title_font_size = 14
    legend_font_size = 14
    value_font_size = 12


class GoogleForestStyle(pygal.style.Style):
    """A Google Spreadsheet Forest theme"""

    background = 'transparent'
    plot_background = 'transparent'
    foreground = '#264540'
    foreground_strong = '#264540'
    foreground_subtle = '#cccccc'
    colors = (
        '#0f6b4f',  # ~ SpringGreen4
        '#388a66',  # ~ sea green
        '#5da68a',  # ~ cadet blue
        '#76b59a',  # ~ dark sea green
        '#8ccfac',  # ~ DarkSeaGreen3
        '#a0dbc1',  # ~ PaleTurquoise3
    )

    value_colors = colors
    font_family = 'Roboto,RobotoDraft,Helvetica,Arial,sans-serif'
    title_font_size = 14
    legend_font_size = 14
    value_font_size = 12


def complete_style_type(type_):
    return type_ if type_.endswith('Style') else '%sStyle' % type_


def parse_args():
    parser = ArgumentParser('pygalgen')
    parser.add_argument('-t', '--type', choices=ARG_TYPES,
                        help=('Output type, default output file extension or '
                              'svg if not specified output'))

    parser.add_argument('-o', '--output',
                        help='Output SVG or PNG file, default STDOUT')

    parser.add_argument('yaml', nargs='?',
                        help='YAML or JSON config, default STDIN')

    args = parser.parse_args()
    if args.type:
        return args

    if args.output:
        try:
            type_ = splitext(args.output)[1][1:]
            if type_ in ARG_TYPES:
                args.type = type_
        except Exception:
            pass
    else:
        args.type = 'svg'

    return args


args = parse_args()
cfg = yaml.load(open(args.yaml) if args.yaml else stdin,
                Loader=yaml.FullLoader)

pygal.style.GoogleClassicStyle = GoogleClassicStyle
pygal.style.GoogleStandardStyle = GoogleStandardStyle
pygal.style.GoogleSimpleLightStyle = GoogleSimpleLightStyle
pygal.style.GoogleStreamlineStyle = GoogleStreamlineStyle
pygal.style.GoogleParadigmStyle = GoogleParadigmStyle
pygal.style.GoogleShiftStyle = GoogleShiftStyle
pygal.style.GoogleMomentumStyle = GoogleMomentumStyle
pygal.style.GoogleEarthyStyle = GoogleEarthyStyle
pygal.style.GoogleEnergeticStyle = GoogleEnergeticStyle
pygal.style.GoogleOceanStyle = GoogleOceanStyle
pygal.style.GoogleCozyStyle = GoogleCozyStyle
pygal.style.GoogleGroovyStyle = GoogleGroovyStyle
pygal.style.GoogleCalmStyle = GoogleCalmStyle
pygal.style.GoogleForestStyle = GoogleForestStyle

raw_type = 'Bar' if args.type == 'html' else cfg.get('type', DEFAULT_TYPE)
type_ = getattr(pygal, raw_type)
config = cfg.get('config', {})


def assign(key, alias=None):
    val = cfg.get(key, cfg.get(alias) if alias else None)
    if val:
        config[key] = val


assign('title')
assign('style')  # Overwrite config['style'] if exists.
assign('x_labels', 'x')
assign('y_labels', 'y')
assign('x_title')
assign('y_title')

if args.type == 'html' and 'x_labels' in config:
    config['x_labels'] = [str(i) for i in config['x_labels']]

style = config.get('style')
if style:
    if isinstance(style, str):
        config['style'] = getattr(pygal.style, complete_style_type(style))
    elif isinstance(style, dict):
        style_type = getattr(
            pygal.style, complete_style_type(style.get('type', DEFAULT_STYLE)))

        del style['type']
        config['style'] = style_type(**style)
    else:
        del config['style']

chart = type_(**config)
for i in cfg.get('series', ()):
    if isinstance(i, dict):
        chart.add(**i)
    elif isinstance(i, (list, tuple)):
        chart.add(title=i[0], values=i[1:])

if args.type == 'svg':
    if args.output:
        chart.render_to_file(args.output)
    else:
        stdout.buffer.write(chart.render())
elif args.type == 'png':
    if args.output:
        chart.render_to_png(args.output)
    else:
        stdout.buffer.write(chart.render_to_png())
elif args.type == 'html':
    chart.value_formatter = lambda x: '∅' if x is None else str(x)
    if args.output:
        open(args.output, 'w').write(chart.render_table(style=True))
    else:
        stdout.write(chart.render_table(style=True))
